// AUTO-GENERATED by build-barrels.js — do not hand-edit the import/export
// list below; re-run the script instead if you add a namespace file.
import BlogPage from "./BlogPage.json";
import CasosDeExito from "./CasosDeExito.json";
import DemoLead from "./DemoLead.json";
import FAQ from "./FAQ.json";
import Footer from "./Footer.json";
import Funcionalidades from "./Funcionalidades.json";
import Hero from "./Hero.json";
import Home from "./Home.json";
import Jsonld from "./Jsonld.json";
import Metadata from "./Metadata.json";
import Navbar from "./Navbar.json";
import PagosVentas from "./PagosVentas.json";
import Precio from "./Precio.json";
import PreciosPage from "./PreciosPage.json";
import Privacidad from "./Privacidad.json";
import Problem from "./Problem.json";
import PromoPopup from "./PromoPopup.json";
import ProofBar from "./ProofBar.json";
import QueObtendras from "./QueObtendras.json";
import Reserva from "./Reserva.json";
import ROICalculator from "./ROICalculator.json";
import Sectores from "./Sectores.json";
import SectoresPage from "./SectoresPage.json";
import SelectorPais from "./SelectorPais.json";
import Servicios from "./Servicios.json";
import Software from "./Software.json";
import Terminos from "./Terminos.json";
import Ubicacion from "./Ubicacion.json";
import WhatsAppFAB from "./WhatsAppFAB.json";
import WhatsAppShowcase from "./WhatsAppShowcase.json";

const messages = {
  BlogPage,
  CasosDeExito,
  DemoLead,
  FAQ,
  Footer,
  Funcionalidades,
  Hero,
  Home,
  Jsonld,
  Metadata,
  Navbar,
  PagosVentas,
  Precio,
  PreciosPage,
  Privacidad,
  Problem,
  PromoPopup,
  ProofBar,
  QueObtendras,
  Reserva,
  ROICalculator,
  Sectores,
  SectoresPage,
  SelectorPais,
  Servicios,
  Software,
  Terminos,
  Ubicacion,
  WhatsAppFAB,
  WhatsAppShowcase,
};

export default messages;
