// Copy strings for ES + EN. Single source of truth.
const COPY = {
  es: {
    nav: { features: 'Funciones', sectors: 'Sectores', pricing: 'Precios', testimonials: 'Casos', faq: 'Preguntas', login: 'Iniciar sesión', cta: 'Probar gratis' },
    hero: {
      pill: 'Nuevo · Plan desde $10 USD/mes',
      h1a: 'Deja de perseguir citas',
      h1b: 'por WhatsApp.',
      h1c: 'Que tu agenda lo haga sola.',
      sub: 'AgenditApp recibe reservas 24/7, confirma con tus clientes por WhatsApp y reduce las inasistencias hasta un 70% — sin que tengas que mover un dedo.',
      cta1: 'Crear mi demo gratis',
      cta2: 'Ver cómo funciona',
      micro: 'Sin tarjeta · Listo en 10 min · Cancela cuando quieras',
      live: 'reserva confirmada hace',
    },
    proof: {
      label: 'Confían en nosotros',
      stats: [
        { n: '200+', l: 'negocios activos' },
        { n: '60%', l: 'menos inasistencias' },
        { n: '24/7', l: 'reservas online' },
        { n: '4.9★', l: 'satisfacción' },
      ],
    },
    problem: {
      eyebrow: 'El verdadero costo de WhatsApp manual',
      h2: '¿Te suena familiar?',
      sub: 'Cada uno de estos momentos te cuesta tiempo, ingresos y energía. AgenditApp los resuelve antes de que sucedan.',
      cols: [
        {
          title: 'Sin AgenditApp',
          tone: 'bad',
          items: [
            { t: '"¿A qué hora era mi cita?"', s: 'Respondes los mismos chats todos los días.' },
            { t: 'Cliente que no llega', s: 'Pierdes el cupo y a otro cliente que sí quería.' },
            { t: 'Agenda en libreta', s: 'Cruces de horario, errores y caos los sábados.' },
            { t: 'Trabajas hasta tarde', s: 'Contestando mensajes en vez de descansar.' },
            { t: 'No sabes cuánto generas', s: 'Sin reportes, sin claridad, sin control.' },
          ],
        },
        {
          title: 'Con AgenditApp',
          tone: 'good',
          items: [
            { t: 'Reservan solas, 24/7', s: 'Tu enlace trabaja mientras duermes.' },
            { t: 'Recordatorios automáticos', s: 'Hasta 70% menos ausencias comprobado.' },
            { t: 'Agenda visual en la nube', s: 'Sin cruces. Desde cualquier dispositivo.' },
            { t: 'WhatsApp en piloto automático', s: 'El sistema confirma, tú atiendes.' },
            { t: 'Reportes claros', s: 'Sabes qué servicio, día y empleado generan más.' },
          ],
        },
      ],
    },
    pillars: {
      eyebrow: '¿Qué obtendrás?',
      h2: 'Tres cambios que sentirás desde la primera semana.',
      sub: 'Las herramientas más valoradas por nuestros usuarios, en una sola plataforma.',
      items: [
        { kicker: 'Control que multiplica ingresos', t: 'Convierte el desorden en claridad.', d: 'Deja atrás las libretas y descubre qué servicios, empleados y clientes generan más. Dispara ventas con campañas de WhatsApp y fidelización.' },
        { kicker: 'Agenda en piloto automático', t: 'Que tu negocio trabaje para ti.', d: 'Olvídate de contestar chats. Tus clientes reservan 24/7, el sistema confirma y envía recordatorios por WhatsApp para acabar con las inasistencias.' },
        { kicker: 'Prestigio que inspira confianza', t: 'Destaca por encima del resto.', d: 'Presencia online impecable bajo tu propia marca y dominio. Administra todo desde tu celular con la tranquilidad de la nube.' },
      ],
    },
    catalog: {
      eyebrow: 'Catálogo de servicios',
      h2: 'Tu menú profesional, siempre actualizado.',
      sub: 'Tus clientes ven precios, duración y descripción antes de reservar. Adiós a "¿cuánto vale?" por WhatsApp.',
      items: [
        { t: 'Precio, duración y detalle', d: 'Configura cada servicio con toda la información. Ideal para combos, paquetes y promos.' },
        { t: 'Organizado por categorías', d: 'Agrupa por tipo: uñas, cabello, faciales, masajes… fácil de navegar.' },
        { t: 'Actualización en tiempo real', d: 'Cambia precios o tiempos cuando quieras. Se refleja al instante.' },
        { t: 'Listo para SEO y Google Maps', d: 'Títulos, descripciones y datos estructurados para que Google te encuentre.' },
      ],
      sample: [
        { cat: 'Uñas', name: 'Manicure gel', dur: '45 min', price: '$45.000' },
        { cat: 'Uñas', name: 'Pedicure spa', dur: '60 min', price: '$55.000' },
        { cat: 'Cabello', name: 'Corte + lavado', dur: '40 min', price: '$35.000' },
        { cat: 'Cabello', name: 'Color completo', dur: '120 min', price: '$120.000' },
        { cat: 'Faciales', name: 'Limpieza profunda', dur: '50 min', price: '$60.000' },
      ],
    },
    location: {
      eyebrow: 'Ubicación',
      h2: 'Que tus clientes lleguen sin preguntar.',
      sub: 'Tu página de reservas muestra la dirección, mapa integrado y acceso directo a Google Maps o Waze.',
      items: [
        { t: 'Dirección exacta visible', d: 'Barrio, ciudad y referencia tal como aparece en Google Maps.' },
        { t: 'Botón "Cómo llegar"', d: 'Un tap abre la ruta en Google Maps o Waze desde el celular.' },
        { t: 'Fácil de compartir', d: 'Enlace por WhatsApp, Instagram o Google Business — llegan sin preguntar.' },
      ],
      placeholder: 'Tu negocio aquí',
      sample: { biz: 'Estudio Rosa', addr: 'Cra. 7 #12-34, Centro · Neiva', cta: 'Abrir en Maps' },
    },
    compare: {
      eyebrow: 'Tabla comparativa',
      h2: 'Revisa en detalle qué incluye cada plan.',
      sub: 'Todos los planes incluyen acceso completo a la plataforma desde el primer día.',
      tip: '¿No sabes cuál elegir? Si quieres reducir ausencias → Esencial. Si quieres crecer con campañas → Marca Propia.',
      groups: [
        { title: 'Base — incluido en todos', rows: [
          { f: 'Reservas y citas ilimitadas (24/7)', v: [true, true, true] },
          { f: 'Panel administrativo y agenda visual', v: [true, true, true] },
          { f: 'Servicios, empleados y clientes', v: [true, true, true] },
          { f: 'Analíticas + comisiones / nómina', v: [true, true, true] },
          { f: 'Fidelidad + branding personalizado', v: [true, true, true] },
        ]},
        { title: 'Presencia web', rows: [
          { f: 'Landing de bienvenida', v: ['Sencilla', 'Sencilla', 'Profesional'] },
          { f: 'Subdominio (tu-negocio.agenditapp.com)', v: [true, true, true] },
          { f: 'Dominio propio (tumarca.com)', v: [false, false, true] },
        ]},
        { title: 'Automatización WhatsApp', rows: [
          { f: 'WhatsApp desde tu número Business', v: [false, true, true] },
          { f: 'Mensaje de agendamiento configurable', v: [true, true, true] },
          { f: 'Recordatorios automáticos', v: [false, '1 recordatorio', '2 recordatorios'] },
          { f: 'Mensajes editables', v: [false, true, true] },
          { f: 'Enlace para confirmar / cancelar citas', v: [false, true, true] },
          { f: 'Campañas masivas de WhatsApp', v: [false, false, true] },
        ]},
      ],
    },
    how: {
      eyebrow: 'Así de simple',
      h2: 'Tus clientes reservan en 4 pasos.',
      sub: 'Sin descargar apps. Sin formularios largos. Solo un enlace que compartes por WhatsApp, Instagram o Google.',
      steps: [
        { n: '01', t: 'Eligen servicio', d: 'Manicure, corte, sesión… ven precios y duración antes de reservar.' },
        { n: '02', t: 'Eligen profesional', d: 'O dejan que el sistema asigne al primero disponible.' },
        { n: '03', t: 'Eligen fecha y hora', d: 'Disponibilidad real, en tiempo real, sin doble booking.' },
        { n: '04', t: 'Reciben WhatsApp', d: 'Confirmación instantánea + recordatorio antes de la cita.' },
      ],
    },
    features: {
      eyebrow: 'Plataforma completa',
      h2: 'Todo lo que necesitas para operar.',
      sub: 'No es solo una agenda. Es el sistema operativo de tu negocio de servicios.',
      items: [
        { t: 'Agenda visual', d: 'Vista por día, semana o profesional. Drag & drop como Google Calendar.', tag: 'Esencial' },
        { t: 'WhatsApp Business', d: 'Confirmaciones y recordatorios desde tu propio número.', tag: 'Diferenciador' },
        { t: 'Catálogo de servicios', d: 'Precios, duración, descripción. Tu menú profesional online.', tag: 'Esencial' },
        { t: 'Equipo y comisiones', d: 'Cada empleado con horario propio. Comisiones automáticas.', tag: 'Pro' },
        { t: 'Marca blanca', d: 'Tu logo, tus colores, tu dominio. Tu marca, no la nuestra.', tag: 'Pro' },
        { t: 'Campañas masivas', d: 'Promos de WhatsApp segmentadas en 2 clics.', tag: 'Pro' },
        { t: 'Fidelización', d: 'Programa de puntos y recompensas integrado.', tag: 'Plus' },
        { t: 'Reportes', d: 'Ingresos, top servicios, retención. Decisiones con datos.', tag: 'Esencial' },
      ],
    },
    wa: {
      eyebrow: 'WhatsApp es nuestro corazón',
      h2: 'El único sistema que habla por ti, en tu número.',
      sub: 'Mientras otros te cobran cada mensaje, nosotros automatizamos confirmación, recordatorios y campañas — todo desde tu WhatsApp Business.',
      bullets: [
        'Confirmación automática al reservar',
        '1 o 2 recordatorios programables',
        'Cliente confirma o cancela con 1 toque',
        'Campañas masivas segmentadas',
        'Mensajes 100% editables a tu tono',
      ],
      chat: [
        { from: 'biz', t: '¡Hola Camila! 👋 Tu cita en Estudio Rosa está confirmada:', meta: '10:32' },
        { from: 'biz', t: '✂️ Manicure Gel · 45 min\n📅 Martes 12 · 3:00 pm\n💵 $45.000', meta: '10:32' },
        { from: 'me', t: '¡Perfecto, ahí estaré! 💅', meta: '10:34' },
        { from: 'biz', t: 'Recordatorio: tu cita es mañana a las 3:00 pm. ¿Sigues asistiendo?', meta: 'Lun 5:00 pm', delay: 1800 },
        { from: 'me', t: '✅ Confirmar', meta: 'Lun 5:01 pm', isButton: true, delay: 2400 },
      ],
    },
    sectors: {
      eyebrow: 'Sectores',
      h2: 'Hecho para cualquier negocio de citas.',
      sub: 'Desde una barbería con un solo asiento hasta un consultorio con 8 profesionales. AgenditApp se adapta.',
      items: [
        { e: '💅', t: 'Salones y uñas' },
        { e: '💈', t: 'Barberías' },
        { e: '🧖', t: 'Spas y masajes' },
        { e: '👁️', t: 'Lashes y cejas' },
        { e: '🩺', t: 'Consultorios médicos' },
        { e: '🦷', t: 'Odontología' },
        { e: '🧠', t: 'Psicología' },
        { e: '🏋️', t: 'Entrenadores' },
        { e: '🎨', t: 'Academias y clases' },
        { e: '✨', t: 'Estética médica' },
      ],
    },
    test: {
      eyebrow: 'Casos reales',
      h2: 'No nos creas a nosotros. Escúchalos a ellas.',
      items: [
        { q: 'Las ausencias bajaron un 60%. Mis clientas agendan solas a cualquier hora y yo me concentro en lo que amo.', n: 'Luisa Fernanda', r: 'Estudio Rosa · Salón de belleza', loc: 'Neiva, Colombia', stat: '−60%', statLabel: 'ausencias' },
        { q: 'Pasé de contestar 80 chats al día a casi cero. Mi WhatsApp ahora vende, no responde.', n: 'Carlos Mendoza', r: 'Barbería El Don', loc: 'San José, Costa Rica', stat: '+3h', statLabel: 'libres al día' },
        { q: 'En 2 meses recuperé el costo del año entero. La campaña de cumpleaños sola me trajo 18 citas nuevas.', n: 'Andrea Pizarro', r: 'Spa Lumen', loc: 'Santiago, Chile', stat: '18×', statLabel: 'ROI campañas' },
      ],
    },
    roi: {
      eyebrow: 'Calcula tu retorno',
      h2: 'Se paga solo con 1 cita recuperada al mes.',
      sub: 'Promedio: nuestros clientes recuperan entre 8 y 20 citas perdidas al mes gracias a recordatorios automáticos.',
      lblTicket: 'Ticket promedio por cita',
      lblNoshows: 'Inasistencias por mes hoy',
      result: 'Recuperas hasta',
      perMonth: 'al mes',
      vs: 'vs $20 USD del plan Esencial',
      payoff: 'Tu inversión se recupera con menos de 1 cita.',
    },
    pricing: {
      eyebrow: 'Precios',
      h2: 'Planes simples. Sin permanencia. Sin sorpresas.',
      sub: 'Empieza por $10 USD/mes. Cambia de plan cuando quieras. Cancela cuando quieras.',
      monthly: 'Mensual',
      yearly: 'Anual · 2 meses gratis',
      plans: [
        {
          name: 'Básico', tag: 'Empieza aquí', price: 10, anchor: 'Ideal para 1 persona', desc: 'Organiza tu agenda y empieza a recibir reservas online.',
          features: ['Reservas y citas ilimitadas 24/7', 'Panel administrativo completo', 'Servicios, empleados y clientes', 'Subdominio tu-negocio.agenditapp.com', 'Soporte por WhatsApp']
        },
        {
          name: 'Esencial', tag: 'Más elegido ★', price: 20, anchor: 'Para reducir ausencias', desc: 'Automatiza WhatsApp y reduce inasistencias hasta 70%.', highlight: true,
          features: ['Todo lo del plan Básico', 'WhatsApp desde tu número Business', '1 recordatorio automático', 'Enlace de confirmar/cancelar', 'Mensajes editables a tu tono']
        },
        {
          name: 'Marca Propia', tag: 'Pro', price: 30, anchor: 'Para crecer y vender más', desc: 'Tu marca, tu dominio, campañas masivas de WhatsApp.',
          features: ['Todo lo del plan Esencial', 'Dominio propio (tumarca.com)', '2 recordatorios automáticos', 'Campañas masivas WhatsApp', 'Landing profesional con SEO']
        },
      ],
      cta: 'Empezar ahora',
      guarantee: '7 días de garantía · Sin tarjeta para probar · Migración gratis',
    },
    faq: {
      eyebrow: 'Preguntas frecuentes',
      h2: 'Antes de empezar, resolvamos tus dudas.',
      items: [
        { q: '¿Realmente no tiene permanencia?', a: 'Correcto. El pago es mes a mes y puedes cancelar cuando quieras sin penalizaciones ni cláusulas. Si te vas, te ayudamos a exportar tus clientes y agenda.' },
        { q: '¿Los recordatorios salen desde mi número de WhatsApp?', a: 'Sí. En los planes Esencial y Marca Propia, los mensajes se envían desde tu número oficial de WhatsApp Business. Tu cliente ve tu marca, no la nuestra.' },
        { q: '¿Necesito instalar algo o comprar equipos?', a: 'No. AgenditApp funciona 100% en la nube. Lo abres desde tu celular, tablet o computadora. Configuramos todo contigo en una llamada de 30 minutos.' },
        { q: '¿En cuánto tiempo lo tengo funcionando?', a: 'En el mismo día. Te ayudamos a cargar servicios, horarios y empleados, y dejamos tu enlace de reservas listo para compartir.' },
        { q: '¿Y si soy malo con la tecnología?', a: 'AgenditApp se diseñó para personas no técnicas. Y nuestro equipo te configura todo gratis al inicio. Si tu mamá puede usar WhatsApp, puede usar AgenditApp.' },
        { q: '¿Puedo cambiar de plan después?', a: 'Sí, hacia arriba o hacia abajo, cuando quieras. Solo pagas la diferencia prorrateada del mes en curso.' },
        { q: '¿Qué pasa con mis datos y los de mis clientes?', a: 'Tu información está cifrada y respaldada en la nube. Solo tú accedes con tu cuenta. Cumplimos con normativas de protección de datos en LatAm.' },
        { q: '¿Aceptan transferencias o Nequi/Daviplata?', a: 'Sí. Aceptamos transferencia bancaria, Nequi, Daviplata y tarjetas internacionales.' },
      ],
    },
    demo: {
      eyebrow: 'Demo personalizada',
      h2: 'Te dejamos la agenda lista en 30 minutos.',
      sub: 'Cuéntanos sobre tu negocio y te contactamos por WhatsApp para configurar tus servicios y mostrarte el panel completo.',
      f: { name: 'Tu nombre', biz: 'Nombre del negocio', wa: 'WhatsApp', type: 'Tipo de negocio', vol: 'Citas al mes', send: 'Quiero mi demo gratis' },
      types: ['Selecciona…', 'Salón / Uñas', 'Barbería', 'Spa / Masajes', 'Lashes / Cejas', 'Entrenador / Fitness', 'Consultorio médico', 'Psicología', 'Odontología', 'Estética médica', 'Academia / Cursos', 'Otro'],
      vols: ['Selecciona…', 'Menos de 50', '50 – 150', '150 – 300', 'Más de 300'],
      promise: ['Respuesta en menos de 1 hora', 'Configuración gratis incluida', 'Sin compromiso de compra'],
      altTitle: '¿Prefieres hablar directo?',
      altBody: 'Escríbenos por WhatsApp y un asesor te muestra una demo en vivo en menos de 5 minutos.',
      altCta: 'Hablar por WhatsApp',
    },
    finalCta: {
      eyebrow: '¿Listo?',
      h2: 'Tu próxima cita podría reservarse mientras lees esto.',
      sub: 'Únete a más de 200 negocios en Latinoamérica que ya reciben reservas 24/7.',
      cta1: 'Crear mi demo gratis',
      cta2: 'Ver planes y precios',
    },
    footer: {
      tagline: 'Sistema de agendamiento online para negocios de belleza, bienestar y servicios profesionales en Latinoamérica.',
      cols: [
        { t: 'Producto', l: ['Funciones', 'Sectores', 'Precios', 'Blog'] },
        { t: 'Sectores', l: ['Salones de belleza', 'Barberías', 'Spas', 'Consultorios', 'Psicología', 'Odontología'] },
        { t: 'Empresa', l: ['Términos', 'Privacidad', 'Soporte', 'Estado del sistema'] },
      ],
      copy: '© 2026 AgenditApp · Hecho con ❤️ para negocios que viven de las citas.',
      regions: 'Colombia · México · Costa Rica · Chile · y más',
    },
  },
  en: {
    nav: { features: 'Features', sectors: 'Industries', pricing: 'Pricing', testimonials: 'Stories', faq: 'FAQ', login: 'Sign in', cta: 'Try for free' },
    hero: {
      pill: 'New · Plans from $10 USD/mo',
      h1a: 'Stop chasing bookings',
      h1b: 'on WhatsApp.',
      h1c: 'Let your calendar work for you.',
      sub: 'AgenditApp accepts bookings 24/7, confirms with clients on WhatsApp, and cuts no-shows by up to 70% — without you lifting a finger.',
      cta1: 'Start free demo',
      cta2: 'See how it works',
      micro: 'No card · Live in 10 min · Cancel anytime',
      live: 'booking confirmed',
    },
    proof: { label: 'Trusted by', stats: [{ n: '200+', l: 'active businesses' }, { n: '60%', l: 'fewer no-shows' }, { n: '24/7', l: 'online bookings' }, { n: '4.9★', l: 'satisfaction' }] },
    problem: {
      eyebrow: 'The real cost of manual WhatsApp',
      h2: 'Sound familiar?',
      sub: 'Each of these moments costs you time, revenue, and energy. AgenditApp prevents them before they happen.',
      cols: [
        { title: 'Without AgenditApp', tone: 'bad', items: [
          { t: '"What time was my appointment?"', s: 'You answer the same chats every day.' },
          { t: 'Client no-show', s: 'You lose the slot and another client who wanted it.' },
          { t: 'Paper calendar', s: 'Double bookings, errors, chaos on Saturdays.' },
          { t: 'Working late', s: 'Replying to messages instead of resting.' },
          { t: 'No clue what you earn', s: 'No reports, no clarity, no control.' },
        ]},
        { title: 'With AgenditApp', tone: 'good', items: [
          { t: 'They book themselves, 24/7', s: 'Your link works while you sleep.' },
          { t: 'Automatic reminders', s: 'Up to 70% fewer no-shows, proven.' },
          { t: 'Visual cloud calendar', s: 'No conflicts. Any device.' },
          { t: 'WhatsApp on autopilot', s: 'The system confirms, you focus.' },
          { t: 'Clear reports', s: 'Know which service, day and staff make most.' },
        ]},
      ],
    },
    pillars: {
      eyebrow: 'What you get',
      h2: 'Three shifts you\'ll feel from week one.',
      sub: 'The most-loved tools, in one platform.',
      items: [
        { kicker: 'Control that multiplies revenue', t: 'Turn chaos into clarity.', d: 'Leave paper behind. See which services, staff and clients make most. Boost sales with WhatsApp campaigns and loyalty.' },
        { kicker: 'Calendar on autopilot', t: 'Let your business work for you.', d: 'Stop replying to chats. Clients book 24/7, the system confirms and sends reminders via WhatsApp — goodbye no-shows.' },
        { kicker: 'Prestige that builds trust', t: 'Stand out from the rest.', d: 'Flawless online presence under your own brand and domain. Run everything from your phone, safely in the cloud.' },
      ],
    },
    catalog: {
      eyebrow: 'Service catalog',
      h2: 'Your professional menu, always up to date.',
      sub: 'Clients see prices, duration and description before booking. No more "how much?" on WhatsApp.',
      items: [
        { t: 'Price, duration and detail', d: 'Configure each service with full info. Great for combos, bundles and promos.' },
        { t: 'Organized by category', d: 'Group by type: nails, hair, facials, massage… easy to browse.' },
        { t: 'Real-time updates', d: 'Change prices or times anytime. Reflected instantly.' },
        { t: 'SEO + Google Maps ready', d: 'Titles, descriptions and structured data so Google finds you.' },
      ],
      sample: [
        { cat: 'Nails', name: 'Gel manicure', dur: '45 min', price: '$45.000' },
        { cat: 'Nails', name: 'Spa pedicure', dur: '60 min', price: '$55.000' },
        { cat: 'Hair', name: 'Cut + wash', dur: '40 min', price: '$35.000' },
        { cat: 'Hair', name: 'Full color', dur: '120 min', price: '$120.000' },
        { cat: 'Facials', name: 'Deep cleanse', dur: '50 min', price: '$60.000' },
      ],
    },
    location: {
      eyebrow: 'Location',
      h2: 'Help clients arrive without asking.',
      sub: 'Your booking page shows the address, embedded map and direct access to Google Maps or Waze.',
      items: [
        { t: 'Exact address visible', d: 'Neighborhood, city and reference as on Google Maps.' },
        { t: '"Get directions" button', d: 'One tap opens the route in Google Maps or Waze.' },
        { t: 'Easy to share', d: 'Link on WhatsApp, Instagram or Google Business — they just arrive.' },
      ],
      placeholder: 'Your business here',
      sample: { biz: 'Estudio Rosa', addr: 'Cra. 7 #12-34, Downtown · Neiva', cta: 'Open in Maps' },
    },
    compare: {
      eyebrow: 'Compare plans',
      h2: 'See exactly what\'s in each plan.',
      sub: 'All plans include full access to the platform from day one.',
      tip: 'Not sure which? To cut no-shows → Essential. To grow with campaigns → Own Brand.',
      groups: [
        { title: 'Core — in every plan', rows: [
          { f: 'Unlimited bookings (24/7)', v: [true, true, true] },
          { f: 'Admin panel + visual calendar', v: [true, true, true] },
          { f: 'Services, staff and clients', v: [true, true, true] },
          { f: 'Analytics + commissions / payroll', v: [true, true, true] },
          { f: 'Loyalty + custom branding', v: [true, true, true] },
        ]},
        { title: 'Web presence', rows: [
          { f: 'Welcome landing', v: ['Simple', 'Simple', 'Pro'] },
          { f: 'Subdomain (your-biz.agenditapp.com)', v: [true, true, true] },
          { f: 'Own domain (yourbrand.com)', v: [false, false, true] },
        ]},
        { title: 'WhatsApp automation', rows: [
          { f: 'WhatsApp from your Business number', v: [false, true, true] },
          { f: 'Editable booking message', v: [true, true, true] },
          { f: 'Automatic reminders', v: [false, '1 reminder', '2 reminders'] },
          { f: 'Editable messages', v: [false, true, true] },
          { f: 'Confirm / cancel link', v: [false, true, true] },
          { f: 'Mass WhatsApp campaigns', v: [false, false, true] },
        ]},
      ],
    },
    how: { eyebrow: 'This simple', h2: 'Your clients book in 4 steps.', sub: 'No app downloads. No long forms. Just a link you share on WhatsApp, Instagram or Google.',
      steps: [
        { n: '01', t: 'Pick service', d: 'Manicure, haircut, session… they see prices and duration upfront.' },
        { n: '02', t: 'Pick staff', d: 'Or let the system assign the first available.' },
        { n: '03', t: 'Pick date and time', d: 'Real availability, real time, no double booking.' },
        { n: '04', t: 'Get WhatsApp', d: 'Instant confirmation + reminder before the visit.' },
      ],
    },
    features: { eyebrow: 'Complete platform', h2: 'Everything you need to run.', sub: 'Not just a calendar. The OS for your service business.', items: [
      { t: 'Visual calendar', d: 'Day, week or staff view. Drag & drop like Google Calendar.', tag: 'Core' },
      { t: 'WhatsApp Business', d: 'Confirmations and reminders from your own number.', tag: 'Differentiator' },
      { t: 'Service catalog', d: 'Prices, duration, description. Your professional menu online.', tag: 'Core' },
      { t: 'Team & commissions', d: 'Each employee with own schedule. Auto commissions.', tag: 'Pro' },
      { t: 'White label', d: 'Your logo, colors, domain. Your brand, not ours.', tag: 'Pro' },
      { t: 'Mass campaigns', d: 'Segmented WhatsApp promos in 2 clicks.', tag: 'Pro' },
      { t: 'Loyalty', d: 'Built-in points and rewards program.', tag: 'Plus' },
      { t: 'Reports', d: 'Revenue, top services, retention. Data-driven decisions.', tag: 'Core' },
    ]},
    wa: { eyebrow: 'WhatsApp is our heart', h2: 'The only system that talks for you, on your number.',
      sub: 'While others charge per message, we automate confirmations, reminders and campaigns — all from your WhatsApp Business.',
      bullets: ['Auto-confirmation on booking', '1 or 2 schedulable reminders', 'Client confirms or cancels with 1 tap', 'Mass segmented campaigns', '100% editable messages, your tone'],
      chat: [
        { from: 'biz', t: 'Hi Camila! 👋 Your appointment at Rosa Studio is confirmed:', meta: '10:32' },
        { from: 'biz', t: '✂️ Gel Manicure · 45 min\n📅 Tue 12 · 3:00 pm\n💵 $45.000', meta: '10:32' },
        { from: 'me', t: 'Perfect, see you there! 💅', meta: '10:34' },
        { from: 'biz', t: 'Reminder: your appointment is tomorrow at 3:00 pm. Still coming?', meta: 'Mon 5:00 pm', delay: 1800 },
        { from: 'me', t: '✅ Confirm', meta: 'Mon 5:01 pm', isButton: true, delay: 2400 },
      ],
    },
    sectors: { eyebrow: 'Industries', h2: 'Built for any appointment business.', sub: 'From a one-chair barbershop to a clinic with 8 pros. AgenditApp adapts.', items: [
      { e: '💅', t: 'Salons & nails' }, { e: '💈', t: 'Barbershops' }, { e: '🧖', t: 'Spas & massage' }, { e: '👁️', t: 'Lashes & brows' },
      { e: '🩺', t: 'Medical clinics' }, { e: '🦷', t: 'Dental' }, { e: '🧠', t: 'Psychology' }, { e: '🏋️', t: 'Trainers' },
      { e: '🎨', t: 'Academies' }, { e: '✨', t: 'Med-spa' },
    ]},
    test: { eyebrow: 'Real stories', h2: 'Don\'t take our word. Hear theirs.', items: [
      { q: 'No-shows dropped 60%. My clients book themselves anytime and I focus on what I love.', n: 'Luisa Fernanda', r: 'Estudio Rosa · Beauty salon', loc: 'Neiva, Colombia', stat: '−60%', statLabel: 'no-shows' },
      { q: 'I went from 80 chats a day to almost zero. My WhatsApp now sells, it doesn\'t reply.', n: 'Carlos Mendoza', r: 'Barbershop El Don', loc: 'San José, Costa Rica', stat: '+3h', statLabel: 'free per day' },
      { q: 'In 2 months I covered the whole year. The birthday campaign alone brought me 18 new bookings.', n: 'Andrea Pizarro', r: 'Spa Lumen', loc: 'Santiago, Chile', stat: '18×', statLabel: 'campaign ROI' },
    ]},
    roi: { eyebrow: 'Calculate your return', h2: 'Pays for itself with 1 recovered booking.', sub: 'Average: our clients recover between 8 and 20 lost bookings per month thanks to automatic reminders.',
      lblTicket: 'Average ticket per booking', lblNoshows: 'No-shows per month today', result: 'You recover up to', perMonth: 'per month', vs: 'vs $20 USD on the Essential plan', payoff: 'Your investment pays back with less than 1 booking.' },
    pricing: { eyebrow: 'Pricing', h2: 'Simple plans. No commitment. No surprises.', sub: 'Start at $10 USD/mo. Switch plans anytime. Cancel anytime.', monthly: 'Monthly', yearly: 'Yearly · 2 months free',
      plans: [
        { name: 'Basic', tag: 'Start here', price: 10, anchor: 'Ideal for 1 person', desc: 'Organize your calendar and start receiving bookings.', features: ['Unlimited bookings 24/7', 'Full admin panel', 'Services, staff, clients', 'Subdomain your-biz.agenditapp.com', 'WhatsApp support'] },
        { name: 'Essential', tag: 'Most picked ★', price: 20, anchor: 'Reduce no-shows', desc: 'Automate WhatsApp and cut no-shows by 70%.', highlight: true, features: ['Everything in Basic', 'WhatsApp from your Business number', '1 automatic reminder', 'Confirm/cancel link', 'Editable messages, your tone'] },
        { name: 'Own Brand', tag: 'Pro', price: 30, anchor: 'Grow and sell more', desc: 'Your brand, your domain, mass WhatsApp campaigns.', features: ['Everything in Essential', 'Own domain (yourbrand.com)', '2 automatic reminders', 'Mass WhatsApp campaigns', 'Pro landing with SEO'] },
      ], cta: 'Start now', guarantee: '7-day guarantee · No card to try · Free migration' },
    faq: { eyebrow: 'FAQ', h2: 'Before you start, let\'s answer your questions.', items: [
      { q: 'Truly no commitment?', a: 'Correct. Payment is monthly and you can cancel anytime with no penalty. If you leave, we help you export your clients and calendar.' },
      { q: 'Do reminders go out from my WhatsApp number?', a: 'Yes. On Essential and Own Brand plans, messages are sent from your official WhatsApp Business number. Your client sees your brand, not ours.' },
      { q: 'Do I need to install anything or buy equipment?', a: 'No. AgenditApp runs 100% in the cloud. Open it from your phone, tablet or computer. We set everything up with you in a 30-minute call.' },
      { q: 'How fast can I be live?', a: 'Same day. We help you load services, schedules and staff, and your booking link is ready to share.' },
      { q: 'What if I\'m bad with tech?', a: 'AgenditApp is built for non-technical people. Our team configures it for you for free. If your mom can use WhatsApp, she can use AgenditApp.' },
      { q: 'Can I change plans later?', a: 'Yes, up or down, anytime. You only pay the prorated difference of the current month.' },
      { q: 'What about my data and my clients\' data?', a: 'Your information is encrypted and backed up in the cloud. Only you access with your account. Compliant with LatAm data regulations.' },
      { q: 'Do you accept transfers or Nequi/Daviplata?', a: 'Yes. Bank transfer, Nequi, Daviplata and international cards.' },
    ]},
    demo: { eyebrow: 'Personalized demo', h2: 'We hand you a ready calendar in 30 minutes.', sub: 'Tell us about your business and we\'ll reach out on WhatsApp to set up your services and walk you through the full panel.',
      f: { name: 'Your name', biz: 'Business name', wa: 'WhatsApp', type: 'Business type', vol: 'Bookings/month', send: 'Get my free demo' },
      types: ['Select…', 'Salon / Nails', 'Barbershop', 'Spa / Massage', 'Lashes / Brows', 'Trainer / Fitness', 'Medical clinic', 'Psychology', 'Dental', 'Med-spa', 'Academy / Courses', 'Other'],
      vols: ['Select…', 'Less than 50', '50 – 150', '150 – 300', 'More than 300'],
      promise: ['Reply in under 1 hour', 'Free setup included', 'No purchase commitment'],
      altTitle: 'Prefer to talk live?', altBody: 'Message us on WhatsApp and an advisor shows you a live demo in under 5 minutes.', altCta: 'Chat on WhatsApp' },
    finalCta: { eyebrow: 'Ready?', h2: 'Your next booking could be coming in while you read this.', sub: 'Join 200+ businesses across Latin America already taking bookings 24/7.', cta1: 'Start my free demo', cta2: 'See plans & pricing' },
    footer: { tagline: 'Online appointment software for beauty, wellness and professional service businesses in Latin America.',
      cols: [
        { t: 'Product', l: ['Features', 'Industries', 'Pricing', 'Blog'] },
        { t: 'Industries', l: ['Beauty salons', 'Barbershops', 'Spas', 'Clinics', 'Psychology', 'Dental'] },
        { t: 'Company', l: ['Terms', 'Privacy', 'Support', 'System status'] },
      ], copy: '© 2026 AgenditApp · Made with ❤️ for businesses that live on appointments.', regions: 'Colombia · Mexico · Costa Rica · Chile · and more' },
  },
};

// Real production links — keep in sync with live site
const LINKS = {
  signup: 'https://app.agenditapp.com/signup',
  whatsapp: 'https://wa.me/573184345284?text=Hola%20%F0%9F%91%8B%20quiero%20mi%20demo%20de%20AgenditApp%20para%20mi%20negocio',
  features: 'https://agenditapp.com/funcionalidades',
  sectors: 'https://agenditapp.com/sectores',
  pricing: 'https://agenditapp.com/precios',
  blog: 'https://agenditapp.com/blog',
  terms: 'https://agenditapp.com/terminos',
  privacy: 'https://agenditapp.com/privacidad',
  logo: 'https://agenditapp.com/_next/image?url=%2Flogo-text.png&w=384&q=75',
  screenshots: {
    agenda: 'https://agenditapp.com/screenshots/agenda-virtual-desktop.png',
    booking: 'https://agenditapp.com/screenshots/reserva-paso-1-mockup.png',
    catalog: 'https://agenditapp.com/screenshots/servicios-precios-mockup.png',
    location: 'https://agenditapp.com/screenshots/ubicacion-mockup.png',
  },
};

window.COPY = COPY;
window.LINKS = LINKS;
