export interface Pais {
  codigo: string; // ISO 3166-1 alpha-2
  nombre: string;
  bandera: string;
  dial: string; // Ej: "+57"
}

/** Lista completa de países ordenada: LATAM primero, luego resto del mundo. */
export const PAISES: Pais[] = [
  // ── Latinoamérica ──────────────────────────────────────────────────────────
  { codigo: "CO", nombre: "Colombia", bandera: "🇨🇴", dial: "+57" },
  { codigo: "MX", nombre: "México", bandera: "🇲🇽", dial: "+52" },
  { codigo: "AR", nombre: "Argentina", bandera: "🇦🇷", dial: "+54" },
  { codigo: "CL", nombre: "Chile", bandera: "🇨🇱", dial: "+56" },
  { codigo: "PE", nombre: "Perú", bandera: "🇵🇪", dial: "+51" },
  { codigo: "VE", nombre: "Venezuela", bandera: "🇻🇪", dial: "+58" },
  { codigo: "EC", nombre: "Ecuador", bandera: "🇪🇨", dial: "+593" },
  { codigo: "BO", nombre: "Bolivia", bandera: "🇧🇴", dial: "+591" },
  { codigo: "PY", nombre: "Paraguay", bandera: "🇵🇾", dial: "+595" },
  { codigo: "UY", nombre: "Uruguay", bandera: "🇺🇾", dial: "+598" },
  { codigo: "CR", nombre: "Costa Rica", bandera: "🇨🇷", dial: "+506" },
  { codigo: "GT", nombre: "Guatemala", bandera: "🇬🇹", dial: "+502" },
  { codigo: "SV", nombre: "El Salvador", bandera: "🇸🇻", dial: "+503" },
  { codigo: "HN", nombre: "Honduras", bandera: "🇭🇳", dial: "+504" },
  { codigo: "NI", nombre: "Nicaragua", bandera: "🇳🇮", dial: "+505" },
  { codigo: "PA", nombre: "Panamá", bandera: "🇵🇦", dial: "+507" },
  { codigo: "DO", nombre: "República Dominicana", bandera: "🇩🇴", dial: "+1" },
  { codigo: "PR", nombre: "Puerto Rico", bandera: "🇵🇷", dial: "+1" },
  { codigo: "CU", nombre: "Cuba", bandera: "🇨🇺", dial: "+53" },
  { codigo: "BR", nombre: "Brasil", bandera: "🇧🇷", dial: "+55" },
  // ── Europa ─────────────────────────────────────────────────────────────────
  { codigo: "ES", nombre: "España", bandera: "🇪🇸", dial: "+34" },
  { codigo: "US", nombre: "Estados Unidos", bandera: "🇺🇸", dial: "+1" },
  { codigo: "CA", nombre: "Canadá", bandera: "🇨🇦", dial: "+1" },
  { codigo: "GB", nombre: "Reino Unido", bandera: "🇬🇧", dial: "+44" },
  { codigo: "DE", nombre: "Alemania", bandera: "🇩🇪", dial: "+49" },
  { codigo: "FR", nombre: "Francia", bandera: "🇫🇷", dial: "+33" },
  { codigo: "IT", nombre: "Italia", bandera: "🇮🇹", dial: "+39" },
  { codigo: "PT", nombre: "Portugal", bandera: "🇵🇹", dial: "+351" },
  { codigo: "NL", nombre: "Países Bajos", bandera: "🇳🇱", dial: "+31" },
  { codigo: "BE", nombre: "Bélgica", bandera: "🇧🇪", dial: "+32" },
  { codigo: "CH", nombre: "Suiza", bandera: "🇨🇭", dial: "+41" },
  { codigo: "AT", nombre: "Austria", bandera: "🇦🇹", dial: "+43" },
  { codigo: "SE", nombre: "Suecia", bandera: "🇸🇪", dial: "+46" },
  { codigo: "NO", nombre: "Noruega", bandera: "🇳🇴", dial: "+47" },
  { codigo: "DK", nombre: "Dinamarca", bandera: "🇩🇰", dial: "+45" },
  { codigo: "FI", nombre: "Finlandia", bandera: "🇫🇮", dial: "+358" },
  { codigo: "PL", nombre: "Polonia", bandera: "🇵🇱", dial: "+48" },
  { codigo: "RU", nombre: "Rusia", bandera: "🇷🇺", dial: "+7" },
  { codigo: "UA", nombre: "Ucrania", bandera: "🇺🇦", dial: "+380" },
  { codigo: "RO", nombre: "Rumanía", bandera: "🇷🇴", dial: "+40" },
  { codigo: "CZ", nombre: "República Checa", bandera: "🇨🇿", dial: "+420" },
  { codigo: "HU", nombre: "Hungría", bandera: "🇭🇺", dial: "+36" },
  { codigo: "GR", nombre: "Grecia", bandera: "🇬🇷", dial: "+30" },
  { codigo: "TR", nombre: "Turquía", bandera: "🇹🇷", dial: "+90" },
  { codigo: "IE", nombre: "Irlanda", bandera: "🇮🇪", dial: "+353" },
  { codigo: "SK", nombre: "Eslovaquia", bandera: "🇸🇰", dial: "+421" },
  { codigo: "HR", nombre: "Croacia", bandera: "🇭🇷", dial: "+385" },
  { codigo: "BG", nombre: "Bulgaria", bandera: "🇧🇬", dial: "+359" },
  { codigo: "RS", nombre: "Serbia", bandera: "🇷🇸", dial: "+381" },
  { codigo: "LU", nombre: "Luxemburgo", bandera: "🇱🇺", dial: "+352" },
  // ── Asia ───────────────────────────────────────────────────────────────────
  { codigo: "CN", nombre: "China", bandera: "🇨🇳", dial: "+86" },
  { codigo: "JP", nombre: "Japón", bandera: "🇯🇵", dial: "+81" },
  { codigo: "IN", nombre: "India", bandera: "🇮🇳", dial: "+91" },
  { codigo: "KR", nombre: "Corea del Sur", bandera: "🇰🇷", dial: "+82" },
  { codigo: "ID", nombre: "Indonesia", bandera: "🇮🇩", dial: "+62" },
  { codigo: "PH", nombre: "Filipinas", bandera: "🇵🇭", dial: "+63" },
  { codigo: "PK", nombre: "Pakistán", bandera: "🇵🇰", dial: "+92" },
  { codigo: "BD", nombre: "Bangladés", bandera: "🇧🇩", dial: "+880" },
  { codigo: "VN", nombre: "Vietnam", bandera: "🇻🇳", dial: "+84" },
  { codigo: "TH", nombre: "Tailandia", bandera: "🇹🇭", dial: "+66" },
  { codigo: "MY", nombre: "Malasia", bandera: "🇲🇾", dial: "+60" },
  { codigo: "SG", nombre: "Singapur", bandera: "🇸🇬", dial: "+65" },
  { codigo: "IL", nombre: "Israel", bandera: "🇮🇱", dial: "+972" },
  { codigo: "SA", nombre: "Arabia Saudita", bandera: "🇸🇦", dial: "+966" },
  { codigo: "AE", nombre: "Emiratos Árabes", bandera: "🇦🇪", dial: "+971" },
  { codigo: "EG", nombre: "Egipto", bandera: "🇪🇬", dial: "+20" },
  { codigo: "IR", nombre: "Irán", bandera: "🇮🇷", dial: "+98" },
  { codigo: "IQ", nombre: "Irak", bandera: "🇮🇶", dial: "+964" },
  { codigo: "AF", nombre: "Afganistán", bandera: "🇦🇫", dial: "+93" },
  { codigo: "NP", nombre: "Nepal", bandera: "🇳🇵", dial: "+977" },
  { codigo: "LK", nombre: "Sri Lanka", bandera: "🇱🇰", dial: "+94" },
  { codigo: "MM", nombre: "Myanmar", bandera: "🇲🇲", dial: "+95" },
  { codigo: "KH", nombre: "Camboya", bandera: "🇰🇭", dial: "+855" },
  { codigo: "MN", nombre: "Mongolia", bandera: "🇲🇳", dial: "+976" },
  { codigo: "KZ", nombre: "Kazajistán", bandera: "🇰🇿", dial: "+7" },
  { codigo: "UZ", nombre: "Uzbekistán", bandera: "🇺🇿", dial: "+998" },
  { codigo: "GE", nombre: "Georgia", bandera: "🇬🇪", dial: "+995" },
  { codigo: "AM", nombre: "Armenia", bandera: "🇦🇲", dial: "+374" },
  { codigo: "AZ", nombre: "Azerbaiyán", bandera: "🇦🇿", dial: "+994" },
  { codigo: "JO", nombre: "Jordania", bandera: "🇯🇴", dial: "+962" },
  { codigo: "LB", nombre: "Líbano", bandera: "🇱🇧", dial: "+961" },
  { codigo: "SY", nombre: "Siria", bandera: "🇸🇾", dial: "+963" },
  { codigo: "KW", nombre: "Kuwait", bandera: "🇰🇼", dial: "+965" },
  { codigo: "QA", nombre: "Catar", bandera: "🇶🇦", dial: "+974" },
  { codigo: "BH", nombre: "Baréin", bandera: "🇧🇭", dial: "+973" },
  { codigo: "OM", nombre: "Omán", bandera: "🇴🇲", dial: "+968" },
  { codigo: "YE", nombre: "Yemen", bandera: "🇾🇪", dial: "+967" },
  // ── África ─────────────────────────────────────────────────────────────────
  { codigo: "NG", nombre: "Nigeria", bandera: "🇳🇬", dial: "+234" },
  { codigo: "ZA", nombre: "Sudáfrica", bandera: "🇿🇦", dial: "+27" },
  { codigo: "KE", nombre: "Kenia", bandera: "🇰🇪", dial: "+254" },
  { codigo: "ET", nombre: "Etiopía", bandera: "🇪🇹", dial: "+251" },
  { codigo: "GH", nombre: "Ghana", bandera: "🇬🇭", dial: "+233" },
  { codigo: "TZ", nombre: "Tanzania", bandera: "🇹🇿", dial: "+255" },
  { codigo: "MA", nombre: "Marruecos", bandera: "🇲🇦", dial: "+212" },
  { codigo: "DZ", nombre: "Argelia", bandera: "🇩🇿", dial: "+213" },
  { codigo: "TN", nombre: "Túnez", bandera: "🇹🇳", dial: "+216" },
  { codigo: "LY", nombre: "Libia", bandera: "🇱🇾", dial: "+218" },
  { codigo: "SD", nombre: "Sudán", bandera: "🇸🇩", dial: "+249" },
  { codigo: "CM", nombre: "Camerún", bandera: "🇨🇲", dial: "+237" },
  { codigo: "CI", nombre: "Costa de Marfil", bandera: "🇨🇮", dial: "+225" },
  { codigo: "SN", nombre: "Senegal", bandera: "🇸🇳", dial: "+221" },
  { codigo: "MG", nombre: "Madagascar", bandera: "🇲🇬", dial: "+261" },
  { codigo: "AO", nombre: "Angola", bandera: "🇦🇴", dial: "+244" },
  { codigo: "MZ", nombre: "Mozambique", bandera: "🇲🇿", dial: "+258" },
  { codigo: "ZW", nombre: "Zimbabue", bandera: "🇿🇼", dial: "+263" },
  { codigo: "ZM", nombre: "Zambia", bandera: "🇿🇲", dial: "+260" },
  { codigo: "UG", nombre: "Uganda", bandera: "🇺🇬", dial: "+256" },
  { codigo: "RW", nombre: "Ruanda", bandera: "🇷🇼", dial: "+250" },
  // ── Oceanía ────────────────────────────────────────────────────────────────
  { codigo: "AU", nombre: "Australia", bandera: "🇦🇺", dial: "+61" },
  { codigo: "NZ", nombre: "Nueva Zelanda", bandera: "🇳🇿", dial: "+64" },
  { codigo: "FJ", nombre: "Fiyi", bandera: "🇫🇯", dial: "+679" },
  { codigo: "PG", nombre: "Papúa Nueva Guinea", bandera: "🇵🇬", dial: "+675" },
];
